In [1]:
import sys
import numpy as np

## Basic Numpy Array

In [2]:
np.array([1 ,2 ,3 ,4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])

In [5]:
print((int(a[0]), int(a[1])))

(1, 2)


In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[1:-1]

array([2, 3])

In [9]:
a[::2] #sequence[start:stop:step]

array([1, 3])

In [14]:
b[0], b[2], b[-1]

(np.float64(0.0), np.float64(1.0), np.float64(2.0))