## Array Types

In [1]:
import sys
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([0, .5, 1, 1.5, 2])

In [3]:
a.dtype

dtype('int64')

In [4]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [5]:
b.dtype

dtype('float64')

In [2]:
a

array([1, 2, 3, 4, 5])

In [6]:
arr = np.array([1, 2, 3, 4], dtype=float)
print(arr)

[1. 2. 3. 4.]


In [7]:
arr = np.array([1,2,3,4], dtype=np.int8)
print(arr)

[1 2 3 4]


In [8]:
c = np.array(['a','b','c','d'])
print(c.dtype)

<U1


In [9]:
d = np.array([{'s': 1}])  # ✅ NumPy will automatically infer dtype
print(d.dtype)

object
